import { db } from "@/db/client";
import { orders, orderItems, customers, channels, syncRuns } from "@/db/schema";
import { eq, and } from "drizzle-orm";

/**
 * Wix eCommerce Orders — search endpoint.
 * Auth: API key generated by the account owner in Wix's API Keys Manager.
 * Required headers: Authorization (the raw key), wix-account-id, and
 * wix-site-id (site-level calls need the site ID even though the key
 * is generated at the account level).
 *
 * NOTE: verify this against the live response once run — Wix's exact
 * field names for line items (price vs priceSummary) have shifted
 * between API versions, and this is written from documentation rather
 * than a live test.
 */
const WIX_ORDERS_SEARCH_URL = "https://www.wixapis.com/ecom/v1/orders/search";

type WixOrder = {
  id: string;
  number?: string;
  createdDate: string;
  buyerInfo?: { email?: string; firstName?: string; lastName?: string };
  priceSummary?: { subtotal?: { amount?: string }; total?: { amount?: string }; discount?: { amount?: string } };
  billingInfo?: { address?: { country?: string } };
  currency?: string;
  lineItems?: Array<{
    id: string;
    productName?: { original?: string };
    quantity?: number;
    price?: { amount?: string };
    totalPriceAfterTax?: { amount?: string };
  }>;
};

async function fetchWixOrders(cursor?: string): Promise<{ orders: WixOrder[]; nextCursor?: string }> {
  const res = await fetch(WIX_ORDERS_SEARCH_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: process.env.WIX_API_KEY!,
      "wix-account-id": process.env.WIX_ACCOUNT_ID!,
      "wix-site-id": process.env.WIX_SITE_ID!,
    },
    body: JSON.stringify({
      search: {
        cursorPaging: { limit: 100, cursor },
      },
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Wix orders search failed: ${res.status} ${body}`);
  }

  const json = await res.json();
  return {
    orders: json.orders ?? [],
    nextCursor: json.metadata?.cursors?.next,
  };
}

async function upsertCustomer(channelId: string, email?: string, name?: string, country?: string, orderedAt?: Date) {
  if (!email) return null;

  const existing = await db.query.customers.findFirst({ where: eq(customers.email, email) });

  if (existing) {
    await db
      .update(customers)
      .set({
        lastOrderAt: orderedAt,
        orderCount: existing.orderCount + 1,
      })
      .where(eq(customers.id, existing.id));
    return existing.id;
  }

  const [created] = await db
    .insert(customers)
    .values({
      email,
      name,
      country,
      firstChannelId: channelId,
      firstOrderAt: orderedAt,
      lastOrderAt: orderedAt,
      orderCount: 1,
    })
    .returning({ id: customers.id });

  return created.id;
}

export async function syncWixOrders() {
  const [run] = await db
    .insert(syncRuns)
    .values({ connector: "wix_orders", status: "running" })
    .returning({ id: syncRuns.id });

  try {
    const channel = await db.query.channels.findFirst({ where: eq(channels.key, "wix") });
    if (!channel) throw new Error("No 'wix' row in channels table — seed it first.");

    let cursor: string | undefined;
    let written = 0;

    do {
      const page = await fetchWixOrders(cursor);

      for (const o of page.orders) {
        const orderedAt = new Date(o.createdDate);
        const gross = Number(o.priceSummary?.total?.amount ?? 0);
        const discount = Number(o.priceSummary?.discount?.amount ?? 0);

        const customerId = await upsertCustomer(
          channel.id,
          o.buyerInfo?.email,
          [o.buyerInfo?.firstName, o.buyerInfo?.lastName].filter(Boolean).join(" ") || undefined,
          o.billingInfo?.address?.country,
          orderedAt
        );

        const existingOrder = await db.query.orders.findFirst({
          where: and(eq(orders.channelId, channel.id), eq(orders.externalOrderId, o.id)),
        });
        if (existingOrder) continue; // already synced, skip

        const [insertedOrder] = await db
          .insert(orders)
          .values({
            channelId: channel.id,
            customerId,
            externalOrderId: o.id,
            orderedAt,
            currency: o.currency ?? "USD",
            gross: String(gross),
            discount: String(discount),
            net: String(gross - discount), // platform/processor fees applied in a later pass
            buyerCountry: o.billingInfo?.address?.country,
            source: "api",
            rawPayload: JSON.stringify(o),
          })
          .returning({ id: orders.id });

        for (const li of o.lineItems ?? []) {
          await db.insert(orderItems).values({
            orderId: insertedOrder.id,
            descriptionRaw: li.productName?.original,
            quantity: li.quantity ?? 1,
            gross: String(Number(li.price?.amount ?? 0)),
            net: String(Number(li.totalPriceAfterTax?.amount ?? li.price?.amount ?? 0)),
          });
        }

        written++;
      }

      cursor = page.nextCursor;
    } while (cursor);

    await db
      .update(syncRuns)
      .set({ status: "ok", finishedAt: new Date(), rowsWritten: written })
      .where(eq(syncRuns.id, run.id));

    return { ok: true, written };
  } catch (err) {
    await db
      .update(syncRuns)
      .set({
        status: "failed",
        finishedAt: new Date(),
        errorMessage: err instanceof Error ? err.message : String(err),
      })
      .where(eq(syncRuns.id, run.id));
    throw err;
  }
}
